"""update disciplines table

Revision ID: 50e70fe328b5
Revises: f4a2fa7b5896
Create Date: 2025-07-01 10:04:04.088050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e70fe328b5'
down_revision: Union[str, Sequence[str], None] = 'f4a2fa7b5896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('weekday', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplines', 'weekday')
    # ### end Alembic commands ###
