"""Update disciplines table

Revision ID: a087ea5b56da
Revises: ce150148c84b
Create Date: 2025-07-07 20:18:06.375128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a087ea5b56da'
down_revision: Union[str, Sequence[str], None] = 'ce150148c84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplines', 'is_active')
    # ### end Alembic commands ###
