"""create disciplines table

Revision ID: ce150148c84b
Revises: 
Create Date: 2025-07-04 10:25:57.294867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce150148c84b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('weekday', sa.String(), nullable=False),
    sa.Column('lecture', sa.Boolean(), nullable=False),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('special_data', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplines')
    # ### end Alembic commands ###
