"""create disciplines table

Revision ID: e8c94ce60f5f
Revises: 
Create Date: 2025-06-30 10:28:21.600444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c94ce60f5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('classroom', sa.String(), nullable=True),
    sa.Column('special_data', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplines')
    # ### end Alembic commands ###
